version: "3.8"
services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - 2181:2181
    volumes: 
      - /datalog
    networks:
      kafka-network:
  kafka1:
    image: confluentinc/cp-kafka:latest
    ports:
      - 19092:19092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:19092
      # - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    restart: unless-stopped
    depends_on:
      - zookeeper
    networks:
      kafka-network:
  kafka2:
    image: confluentinc/cp-kafka:latest
    ports:
      - 29092:29092
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092,PLAINTEXT_HOST://localhost:29092
      # - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    restart: on-failure
    depends_on:
      - zookeeper
    restart: on-failure
    networks:
      kafka-network:
  kafka3:
    image: confluentinc/cp-kafka:latest
    ports:
      - 39092:39092
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9092,PLAINTEXT_HOST://localhost:39092
      # - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    restart: on-failure
    depends_on:
      - zookeeper
    networks:
      kafka-network:
networks:
  kafka-network: